### ISSUE TITLE
KarmaExecuteTests failing in pipeline

### ISSUE THREAD

**Issue by Minal1997** [SAP/karma-ui5#429]
We have integrated Karma for our OPA test automation.
Our OPA test are working properly in our local system but failing in jenkins pipeline. Our application uses Odata v2 services.

**karma.config.js**
```
module.exports = function (config) {
	"use strict";

	config.set({
		preprocessors: {
			'webapp/ext/controller/*.js': [
				'coverage'
			],
			'webapp/Component.js': [
				'coverage'
			]
		},
		frameworks: [
			'ui5'
		],
		coverageReporter: {
			includeAllSources: true,
			dir: './target/coverage',
			reporters: [
				{
					type: 'lcov',
					subdir: 'report',
				}
			]
		},
		reporters: [
			'progress', 'coverage'
		],
		ui5: {
			url: "https://sapui5.hana.ondemand.com/1.84.16/",
			mode: "html",
			testpage: "webapp/test/integration/opaTests.qunit.html"	  
		},
		browsers: [
			'ChromeHeadless'
		],
		singleRun: false,
		captureTimeout: 180000,
		browserDisconnectTolerance: 2,
		browserNoActivityTimeout: 60000,
		reportSlowerThan: 90,
		browserDisconnectTimeout: 60000
	});
};
```

**karma-ci-config.js**

```
module.exports = function(config) {

	require("./karma.conf.js")(config);
	config.set({
		browsers: [
			"ChromeCustom"
		],
		customLaunchers: {
			'ChromeCustom': {
				base: 'WebDriver',
				config: {
					hostname: "localhost",
					port: 4444
				},
				browserName: 'chrome',
				name: 'Karma',
				pseudoActivityInterval: 30000
			}
		},
		singleRun: true
	});
}
```

**Jenkins Logs**

```
[2022-05-10T06:42:30.038Z] info  karmaExecuteTests - > worklist@0.0.1 karma

[2022-05-10T06:42:30.038Z] info  karmaExecuteTests - > karma start karma-ci.conf.js

[2022-05-10T06:42:30.038Z] info  karmaExecuteTests - 

[2022-05-10T06:42:30.987Z] info  karmaExecuteTests - 10 05 2022 06:42:30.871:INFO [karma-server]: Karma v6.3.19 server started at http://localhost:9876/

[2022-05-10T06:42:30.988Z] info  karmaExecuteTests - 10 05 2022 06:42:30.872:INFO [launcher]: Launching browsers ChromeCustom with concurrency unlimited

[2022-05-10T06:42:30.988Z] info  karmaExecuteTests - 10 05 2022 06:42:30.876:INFO [launcher]: Starting browser chrome via Remote WebDriver

[2022-05-10T06:42:31.929Z] info  karmaExecuteTests - 10 05 2022 06:42:31.576:INFO [Chrome 84.0.4147.105 (Linux x86_64)]: Connected on socket vmcmrngWg5A_lbUjAAAB with id 284775

[2022-05-10T06:42:31.929Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64) INFO: '2022-05-10 06:42:31 [opaTests.qunit.html] Device API logging initialized - DEVICE'

[2022-05-10T06:42:31.929Z] info  karmaExecuteTests - 

[2022-05-10T06:42:32.191Z] info  karmaExecuteTests - 

[2022-05-10T06:42:32.191Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:32.192Z] info  karmaExecuteTests - LOG: 'Inside the start app '

[2022-05-10T06:42:32.192Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:32.192Z] info  karmaExecuteTests - LOG: 'Inside Mock Server Hi Team !'

[2022-05-10T06:42:32.192Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - LOG: 'Running the app with mock data!'

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:34.312495 Execute success handler -  sap.ui.test.Opa5'

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:34.316580 Execute success handler -  sap.ui.test.Opa5'

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:34.340080 Executing OPA check function on controls null -  sap.ui.test.Opa5'

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:34.340395 Check function is:

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - function(){return D;} -  sap.ui.test.Opa5'

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:34.340604 Result of check function is: false -  sap.ui.test.Opa5'

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:34.735Z] error karmaExecuteTests - ERROR: '2022-05-10 06:42:34.448625 failed to load JavaScript resource: sap/epd/ieh/worklist/Component-preload.js -  sap.ui.ModuleSystem'

[2022-05-10T06:42:34.735Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:34.996Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:34.741179 Executing OPA check function on controls null -  sap.ui.test.Opa5'

[2022-05-10T06:42:34.996Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:34.996Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:34.741600 Check function is:

[2022-05-10T06:42:34.996Z] info  karmaExecuteTests - function(){return D;} -  sap.ui.test.Opa5'

[2022-05-10T06:42:34.996Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:34.996Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:34.741754 Result of check function is: false -  sap.ui.test.Opa5'

[2022-05-10T06:42:34.996Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:35.257Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:35.142314 Executing OPA check function on controls null -  sap.ui.test.Opa5'

[2022-05-10T06:42:35.257Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:35.257Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:35.142645 Check function is:

[2022-05-10T06:42:35.257Z] info  karmaExecuteTests - function(){return D;} -  sap.ui.test.Opa5'

[2022-05-10T06:42:35.257Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:35.257Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:35.142860 Result of check function is: false -  sap.ui.test.Opa5'

[2022-05-10T06:42:35.257Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:35.827Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:35.561425 Executing OPA check function on controls null -  sap.ui.test.Opa5'

[2022-05-10T06:42:35.827Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:35.827Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:35.561754 Check function is:

[2022-05-10T06:42:35.827Z] info  karmaExecuteTests - function(){return D;} -  sap.ui.test.Opa5'

[2022-05-10T06:42:35.827Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:35.827Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:35.561949 Result of check function is: false -  sap.ui.test.Opa5'

[2022-05-10T06:42:35.827Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:35.827Z] error karmaExecuteTests - ERROR: '2022-05-10 06:42:35.736885 ApplicationController: The model's setting 'RefreshAfterChange' wasn't but is now set to 'false'. -  '

[2022-05-10T06:42:35.827Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.087Z] warn  karmaExecuteTests - WARN: '2022-05-10 06:42:35.907739 No valid cache key segment last modification date provided by OData annotations -  FioriElements: genericUtilities.CacheHelper'

[2022-05-10T06:42:36.087Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.087Z] warn  karmaExecuteTests - WARN: '2022-05-10 06:42:35.908090 No valid cache key segment last modification date provided by OData annotations -  FioriElements: genericUtilities.CacheHelper'

[2022-05-10T06:42:36.087Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.087Z] warn  karmaExecuteTests - WARN: '2022-05-10 06:42:35.911100 TemplateComponent: no valid cache key segment last modification date provided by the OData Model -  FioriElements: genericUtilities.CacheHelper'

[2022-05-10T06:42:36.087Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.087Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:36.057665 Executing OPA check function on controls null -  sap.ui.test.Opa5'

[2022-05-10T06:42:36.087Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.087Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:36.057989 Check function is:

[2022-05-10T06:42:36.087Z] info  karmaExecuteTests - function(){return D;} -  sap.ui.test.Opa5'

[2022-05-10T06:42:36.087Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.087Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:36.058125 Result of check function is: true -  sap.ui.test.Opa5'

[2022-05-10T06:42:36.087Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.087Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:36.062600 Execute success handler -  sap.ui.test.Opa5'

[2022-05-10T06:42:36.087Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:36.138104 Executing OPA check function on controls null -  sap.ui.test.Opa5'

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:36.138435 Check function is:

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests - function(){if(!w.started){w.started=true;P.then(function(){w.done=true;},function(x){w.errorMessage="Error while waiting for promise scheduled on flow"+(x?", details: "+x:"");});}if(w.errorMessage){throw new Error(w.errorMessage);}else{return!!w.done;}} -  sap.ui.test.Opa5'

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:36.138705 Result of check function is: true -  sap.ui.test.Opa5'

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.347Z] error karmaExecuteTests - ERROR: '2022-05-10 06:42:36.194824 sap.ui.comp.navpopover.SemanticObjectController: Service 'CrossApplicationNavigation' could not be obtained -  '

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.347Z] error karmaExecuteTests - ERROR: '2022-05-10 06:42:36.208784 NavigationHandler: UShell service API for CrossApplicationNavigation is not available. -  '

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests - DEBUG: '2022-05-10 06:42:36.233340 There are 0 open XHRs and 1 open FakeXHRs.

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests - FakeXHR: URL: '../../odata/v2/HandoverWorklist/' Method: 'HEAD' Async: 'true'

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests - Stack:     at Object.r [as resolveStackTrace] (https://sapui5.hana.ondemand.com/resources/sap/ui/test/autowaiter/_utils.js:6:117)

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests -     at F.d (https://sapui5.hana.ondemand.com/resources/sap/ui/test/autowaiter/_XHRWaiter.js:6:1332)

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests -     at F.s.FakeXMLHttpRequest.send (https://sapui5.hana.ondemand.com/resources/sap/ui/test/autowaiter/_XHRWaiter.js:6:853)

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests -     at Object.request (https://sapui5.hana.ondemand.com/resources/sap/ui/thirdparty/datajs.js:17:21100)

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests -     at E2 (https://sapui5.hana.ondemand.com/resources/sap/ui/thirdparty/datajs.js:17:12512)

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests -     at Object.o.request (https://sapui5.hana.ondemand.com/resources/sap/ui/thirdparty/datajs.js:17:67141)

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests -     at constructor.Q._request (https://sapui5.hana.ondemand.com/resources/sap/ui/core/library-preload.js:4000:330)

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests -     at a1 (https://sapui5.hana.ondemand.com/resources/sap/ui/core/library-preload.js:3927:777)

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests -     at constructor.Q.refreshSecurityToken (https://sapui5.hana.ondemand.com/resources/sap/ui/core/library-preload.js:3927:912)

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests -     at constructor.<anonymous> (https://sapui5.hana.ondemand.com/resources/sap/ui/core/library-preload.js:3926:246) -  sap.ui.test.autowaiter._XHRWaiter#hasPending'

[2022-05-10T06:42:36.347Z] info  karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

[2022-05-10T06:42:36.607Z] error karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64) ERROR

[2022-05-10T06:42:36.607Z] info  karmaExecuteTests -   Script error.

[2022-05-10T06:42:36.607Z] info  karmaExecuteTests -   at :0:0

[2022-05-10T06:42:36.607Z] error karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 ERROR (0 secs / 0 secs)

[2022-05-10T06:42:36.607Z] error karmaExecuteTests - Chrome 84.0.4147.105 (Linux x86_64): Executed 0 of 1 ERROR (4.425 secs / 0 secs)

[2022-05-10T06:42:36.607Z] info  karmaExecuteTests - 10 05 2022 06:42:36.543:INFO [WebDriver]: Killed Karma test.

[2022-05-10T06:42:36.607Z] info  karmaExecuteTests - fatal error: errorDetails{"category":"test","command":"npm run karma","correlationId":"[https://epdhandover.jaas-gcp.cloud.sap.corp/job/epd-handover/job/intelligentHandover/job/karmatesting_worklist/13/","error":"running](https://epdhandover.jaas-gcp.cloud.sap.corp/job/epd-handover/job/intelligentHandover/job/karmatesting_worklist/13/%22,%22error%22:%22running) command 'npm' failed: cmd.Run() failed: exit status 1","library":"SAP/jenkins-library","message":"failed to execute run command","result":"failure","stepName":"karmaExecuteTests","time":"2022-05-10T06:42:36.559667304Z"}

[2022-05-10T06:42:36.607Z] fatal karmaExecuteTests - failed to execute run command - running command 'npm' failed: cmd.Run() failed: exit status 1

[2022-05-10T06:42:36.607Z] info  karmaExecuteTests - persisting reports to GCS is disabled, because gcsBucketId is empty

[2022-05-10T06:42:36.608Z] info  karmaExecuteTests - Step telemetry data:{"StepStartTime":"2022-05-10 06:41:23.655584874 +0000 UTC","PipelineURLHash":"213bfd7082df9034a5cea401cc43f23ffcecaf1e","BuildURLHash":"85cd4e579e0b580cdf9f085a324fea2e12cf8728","StageName":"Central Build","StepName":"karmaExecuteTests","ErrorCode":"1","StepDuration":"72905","ErrorCategory":"test","CorrelationID":"[https://epdhandover.jaas-gcp.cloud.sap.corp/job/epd-handover/job/intelligentHandover/job/karmatesting_worklist/13/","PiperCommitHash":"3fea61e8b0552e8a8a55bb31f0692c8dc9330b3b","ErrorDetail":{"category":"test","command":"npm](https://epdhandover.jaas-gcp.cloud.sap.corp/job/epd-handover/job/intelligentHandover/job/karmatesting_worklist/13/%22,%22PiperCommitHash%22:%223fea61e8b0552e8a8a55bb31f0692c8dc9330b3b%22,%22ErrorDetail%22:%7B%22category%22:%22test%22,%22command%22:%22npm) run karma","correlationId":"[https://epdhandover.jaas-gcp.cloud.sap.corp/job/epd-handover/job/intelligentHandover/job/karmatesting_worklist/13/","error":"running](https://epdhandover.jaas-gcp.cloud.sap.corp/job/epd-handover/job/intelligentHandover/job/karmatesting_worklist/13/%22,%22error%22:%22running) command 'npm' failed: cmd.Run() failed: exit status 1","library":"SAP/jenkins-library","message":"failed to execute run command","result":"failure","stepName":"karmaExecuteTests","time":"2022-05-10T06:42:36.559667304Z"}}

script returned exit code 1

```
Please let us know if we have missed some configurations.

Thankyou

**Comment by matz3** [comment]
I'm sorry, but just from looking at the configuration there's nothing we can do here.
If it only works locally, there must be something different on the CI setup that causes this issue, which is probably not related to this plugin at first glance. It seems that a WebDriver browser is used instead of chrome headless and probably many other things can be different in the CI environment like OS, networking, ...
